18F/pulse

index.html

I set up a Google Analytics account for the site, turned on the privacy knobs, and started contributing to the DAP.
Fixes #37.

Add DAP and GA

---

.travis.yml
manifest.yml

Adding an initial `manifest.yml` and `.travis.yml` file, refs #40 and #44. I was not sure what we had decided the url for the project was going to be and left that open to be completed in review of this pull request, see https://github.com/18F/dotgov-dashboard/compare/add-manifest-travis-file?expand=1#diff-8f7df7fa0d4d3156b5cf623a87156eceR6.

Initial addition of manifest.yml and .travis.yml.

---

.travis.yml
gulpfile.js
package.json

This PR should be merged once a Travis build passes that runs a few sanity checks:
* `npm install`
* `bower install`
* A new `gulp` task that doesn't pipe to `livereload` or hang.
Fixes #40.

A proper travis.yml

---

.travis.yml
deploy/fabfile.py
deploy/pulse.conf
index.html

This adds a tiny system for a webhook that hits our web server's nginx process, which is proxied to a local hookshot instance which runs a `git pull` on the directory where our static site is.
The `hookshot.js` file was added to `master` instead of `production` by mistake in https://github.com/18F/dotgov-dashboard/commit/4a14218cf57fc3e120dd144a26f1587e525e3960. 9_9 The rest is here.
It's not an ideal system, but it's the one used by 18f.gsa.gov and https.cio.gov, and very very similar to the one used by pages.18f.gov. I can imagine us moving to a CloudFoundry-based system like we're setting up for staging, after we evaluate the tradeoffs there.

Production webhook in place

---

index.html

This adds a quick disclaimer header about us being pre-alpha. It's using dumb inline styles, which can/should be replaced whenever is convenient. I'd prefer to get this merged right away though.

Add a pre-alpha disclaimer header

---

_includes/head.html

This lets us see how Google sees our site, and offers a bunch of helpful analysis.
Access to a verified profile can be shared among multiple teammates, so we should only have to do this once.

Add Google Webmaster Tools verification code

---

assets/data/tables/analytics/domains.json
assets/data/tables/https/domains.json
assets/js/analytics/domains.js
assets/js/https/domains.js
assets/js/utils.js
data/data.py
pages/analytics/domains.html
pages/https/domains.html

Links domains in the DAP and HTTPS "domains" table to their website, in a new tab.
Significantly, this takes advantage of the actual analysis we've already done on domains to link to the correct "canonical" endpoint for a domain. So `nasa.gov` links to `http://www.nasa.gov` without any need for hardcoding!
This also bodes well for analytics.usa.gov -- depending on how we publish this data, analytics.usa.gov could dynamically incorporate this data to remove its hardcoded fixes on the front-end.
Fixes #134.

Link domains to their canonical URLs

---

_includes/head.html
pages/analytics/agencies.html
pages/analytics/domains.html
pages/https/agencies.html
pages/https/domains.html

Cache-busts the CSS and JS files we author in this repository, at site build-time. JS and CSS will still be cached appropriately between site updates/builds.
Fixes #92.

Cache-bust our JS and CSS

---

assets/data/https.csv
assets/data/tables/https/agencies.json
assets/data/tables/https/domains.json
assets/js/https/agencies.js
assets/js/https/domains.js
data/data.py
pages/https/agencies.html
pages/https/domains.html
pages/https/guide.html

This now excludes domains which "downgrade" HTTPS (redirect from `https://` to `http://`) from the calculation of "uses HTTPS" that we make our big % out of.
It drops the % from 34% to 31%. However, it is a more honest assessment of whether a domain Uses HTTPS.
I'm still working on this, to sync the language and guidance on the table. Will update when ready for merge.

Revise HTTPS % methodology

---

_includes/head.html
assets/js/analytics/agencies.js
assets/js/analytics/domains.js
assets/js/https/agencies.js
assets/js/https/domains.js
assets/js/main.js
assets/js/utils.js
assets/js/vendor/querystring.js
data/domains.csv
pages/analytics/domains.html

This adds permalink support for search filters, and uses this feature to add support for filtering domains by agency.
Clicking the HHS domain number will take you to `/https/domains/#q=Department%20of%20Health%20And%20Human%20Services`, which shows the list of domains filtered to those owned by HHS.
Fixes #101, and #118.

Link number of agency domains to a filtered list of their domains

---

assets/data/analytics.csv
assets/data/tables/analytics/agencies.json
assets/data/tables/analytics/domains.json
assets/data/tables/https/agencies.json
assets/data/tables/https/domains.json

This performs a full scan and update of the dataset in Pulse, as of May 29th, 2015.
As input, it uses the .gov domain list [as published here](https://github.com/GSA/data/tree/gh-pages/dotgov-domains) on 2015-03-15. This is the same input as our last scan on April 30th, 2015.
It also uses as input a (not yet publicly) updated CSV that the DAP releases, of participating domains/subdomains that have registered at least 1 visit over the prior 2 weeks. In our last April 30th scan, we used a CSV released around March 15th, so the data is fresher by around 2.5 months.
When rounded, the HTTPS participation % remains the same at **31%**. The DAP participation % rises from **33%** to **43%**.
Note that the eligible domains also shifted a bit, as some domains were reachable during the scan that …

Full data re-scan and update

---

assets/js/https/domains.js

And remove the "No data." descriptor for cases where we do have data (there just aren't any negative issues to call out, among the ones we look for here).
I do this in part because the actual grade link is small and easy to miss -- and even harder to click now that we made the whole row clickable, since the cursor pointer is always-on.

Always link to the SSL Labs report

---

_config.yml
_includes/head.html

This will let search engines prefer our production site, and transfer any PageRank for our staging site to our production site.

Make pulse.cio.gov the canonical URL

---

assets/css/main.css

The collapsed menu wasn't displaying when selected. 
Fixed by updating CSS. 
This also prevents those links from being tabbable while offscreen.

Collapsed menu displays now

---

assets/js/https/domains.js

Links with no text were appearing in the domain table when their grade wasn't provided for ssl. 
These links are removed

Removed blank links

---

.gitignore
deploy/hookshot.js
package.json

Thanks for this cool initiative.
Although not used much by contributors, I decided to clean up deploy/hookshot.js, which also involved adding a package.json.
Switched from `minimalist` to `commander` for most robust cli options
hookshot.js now has `--help` command
deploy/hookshot.js --help
Deferred logging of hookshot 'started' line, until the hookshot server was actually listening on the port.
Quite a minor PR, don't mind if it gets reject!

Added package.json, cleaned up hookshot.js

---

.gitignore
Gemfile.lock
Makefile
_config.yml
assets/data/https.csv
assets/data/tables/analytics/agencies.json
assets/data/tables/analytics/domains.json
assets/data/tables/https/agencies.json
assets/data/tables/https/domains.json
data/meta.json

This data update goes from a scan on **May 29, 2015** to a scan on **June 7, 2015**. (There's another scan in progress now, but I'd like to get this merged so we can see granular differences.)
The DAP data has not changed here (and won't be changing in future updates until DAP speeds up its export process). 
The HTTPS number goes up from **31%** to **32%**. A couple notable things:
* sba.gov and sbir.gov are now unreachable by cURL with default options, they get an "Unknown SSL protocol error". SSL Labs doesn't get blocked in the same way, but indicates they both only support TLSv1.0. When I try cURL with `--tlsv1.0`, I can get through to both sites. When I try it with no options, or with `--tlsv1.2`, I get the same unknown error. I think something changed on those domains over that week, …

Data update - June 7, 2015

---

pages/about.html

Currently they 403 due to a missing `/domains/` path component.

Fix HTTPS and DAP links in About page

---

assets/js/Universal-Federated-Analytics-Min.js

This fixes the DAP snippet to be in full compliance. It's not using the still-yet-to-be-finalized central hosting location, so I moved it to self-hosted for the time being.

Get DAP off of incorrect central snippet, submit agency/subagency params

---

_config.yml

I neglected to manually update `_config.yml` with the scan date. I hotfixed it on `master` and this deploys it to production.
An idea for future work: during the `./update` process, use the (now-versioned) `meta.json` file to automatically update `_config.yml` with the scan date.

Deploy hotfixed scan date to production

---

assets/js/https/domains.js

This adds links to specific sections of https.cio.gov that deal with the referenced technical guidelines (RC4, SHA-1, SSLv3, TLSv1.2, HSTS, preloading).
**This depends on https://github.com/GSA/https/pull/116 being merged first**, otherwise the links will 404.

Add links to https.cio.gov for technical guidelines

---

README.md

Now that https://github.com/18F/domain-scan/pull/36 means domain-scan can auto-download the DAP data, the mechanics are substantially simpler.
I'd like to get to the point where the `.gov` domain list is also at a predictable in-place URL. I filed the work to support it in https://github.com/18F/domain-scan/issues/37, but it also requires change at the .gov registry level.

Simplified data update instructions

---

data/domains.csv

This manually adds [everykidinapark.gov](https://everykidinapark.gov/), which launched last week. We're still waiting on a formal update from the .gov team, so I'm adding this one by hand until we get a new one.
@khandelwal, would you mind pinging us if/when `everykid.gov` goes live?

Add everykidinapark.gov

---

data/domains.csv

This adds sbst.gov to `domains.csv`, in lieu of an official .gov domain update. It will be included in today's data update.
I listed it as a GSA-owned site, due to the branding, description, and contact email address listed on the site.
cc @dhcole

Add sbst.gov to Pulse

---

data/domains.csv

Starting next week, 3 new domains (all held by GSA) are added to the list. We haven't gotten an official update to the second-level domain list in quite some time, so I'm doing these by hand.

Add cloud.gov, pif.gov, presidentialinnovationfellows.gov

---

Makefile
README.md
deploy/fabfile.py
deploy/pulse.conf
templates/layout.html

This updates our deployment process to use fabric to properly deploy a dynamic gunicorn-based Python app. I've tested it and successfully deployed our staging and production apps with it.
To deploy to staging, go to the `deploy/` directory, have fabric ready in your `$PATH` somehow, and run:
```
fab deploy
```
To deploy to production, run:
```
fab deploy --set environment=production
```
For convenience, I've added `make staging` and `make production` commands from the project's root that will `cd` into `deploy/` and run the right command for you and `cd/` out. So you can actually just do:
```
make staging
```
and
```
make production
```
Since Fabric is (**_still_**) Python 2 only, I typically make a virtualenv locked to Python 2 just to hold `fabric`, called `fab`, and switch into it …

Proper deployment for a Python app through fabric

---

data/ineligible/analytics.yml
data/processing.py

This adds a list, with one starting member (`fdms.gov`), of domains ineligible for DAP participation. This list is versioned in the repo as `data/ineligible/analytics.yml`, and is a simple list of domains in YAML format. Any domain in this list will be excluded from DAP eligibility during data loading.

Manage and incorporate a list of ineligible DAP domains

---

static/js/https/agencies.js

This fixes the sorting function for columns listing percent status bars on the HTTPS page. 
I had already fixed this for DAP in 7df7b463dc27b6e43e3c64d1226ca50549dc8445, but apparently didn't think to port it to the HTTPS page.
Fixes #414.

Fix sorting on agency percent bar columns for HTTPS

---

README.md

Adds https://govuk.jamiemagee.co.uk/ to the README, and notes that they're forks, not instances.

Add the govuk version to the README, clarify language

---

static/js/main.js
templates/includes/header.html

Set tabindexes to -1 on mobile menu items when the mobile menu is not open. When mobile menu is open, tabindexes are set to 0 to allow for tab through.
Fixes #436

Mobile menu tabindexes

---

README.md
meta.yml

Uses the new consistent permalink to the latest .gov domains added in https://github.com/GSA/data/pull/32, so that the date of the .gov domain export doesn't have to be manually maintained.
Adds the `make debug` command to the README.

Use new .gov domains (with permalink)

---

static/js/accessibility/a11y.js

A11y pages with a url hash will load with the error div scrolled to the top:
Fixes #416

Anchor tag scroll on a11y page

---

app/views.py
data/update.py

This updates the production scanning process to do a few new things:
* Saves the very detailed `cache/` data, which includes per-domain extended JSON data from each scan, alongside the other scan data.
* Tells Amazon S3 to sync from `live/` to `archive/` within S3 itself, rather than re-copying everything from disk to S3 to do so. This became more important once `cache/` was being synced, since that is a more expensive operation.
* Puts the `tls` (SSL Labs) scanner at the end, since it takes the longest. It's easier to see if anything goes wrong with the others if they happen first.

Small improvements to production scanning and data archiving

---

static/js/accessibility/a11y.js

a11y description variables were changed from `description` to `message` on the `a11y.js` file.

Update a11y description variable

---

Makefile
README.md
data/processing.py
data/update.py
deploy/cron.sh
templates/https/guide.html

This is to the `production` branch, because the `staging` branch is in a state of flux while accessibility work is done. (I may soon do a "catch up" merge of `staging` into `production` and then re-hide the accessibility URLs, so that the branches don't get far afield.)
This uses @dhs-ncats' [`pshtt`](https://github.com/dhs-ncats/pshtt) tool for HTTP scanning. It's meant to be an (almost) drop-in replacement for `site-inspector`. However, it is a standalone tool that only does this one function, it is written in Python (2.X, [for now](https://github.com/dhs-ncats/pshtt/issues/4)), and sees use by others in the federal government.
There are no visible changes to the data, and this should result in nearly the same determination, though the README is different and I swapped out a link in the …

Swap out site-inspector for pshtt

---

data/processing.py

This fixes the detection of legislative and judical branch domains. This will remove legislative and judicial branch domains more effectively for scans where they are not eligible (such as DAP compliance).

Improve branch detection logic to keep up with .gov list

---

app/data.py
data/processing.py
static/js/https/domains.js
templates/https/domains.html

This breaks out a domain's HSTS status and preloaded status. It looks like this:
And this:
This is for a few reasons:
* To call more attention to preloading, and a domain's lack of it (even though it's not required by M-15-13 [though it is [recommended](https://https.cio.gov/guide/#options-for-hsts-compliance)]).
* To call more attention to domains which are preload-ready, but not yet submitted. (This now says `Ready for submission` if it's ready to go.)
* HSTS is calculated on a per-endpoint basis, where preloading is necessarily a domain-wide calculation. They are measuring two different scopes, and mixing them is confusing.
* To allow for domains to be preloaded without actually being "preload ready". This would happen if the Chrome list makes a manual override, which could happen for …

Breaks out preloaded and HSTS columns

---

templates/https/guide.html

Update the documentation at `/https/guidance/` to reflect the changes made in #517, where we split out HSTS and preloading into two separate fields and columns.

Document the HSTS/preload field split

---

app/views.py

This re-hides the accessibility URLs on production, which needed to be re-done after the cross-merge.

Hide accessibility URLs

---

app/views.py
static/js/https/domains.js

The HTTPS columns were getting sorted with the `0` values before the `-1` values, for reasons I don't totally understand. However, converting all values to strings before sorting fixes this, and makes more conceptual sense besides.

Fix sort order on HTTPS table

---

static/js/utils.js

The error buttons were using the canonical URL instead of the domain to form permalinks, so it was going to `/accessibility/domain/www.data.gov` instead of `/accessibility/domain/data.gov`, which caused it to not be able to look up the data by domain in `a11y.json`.
This fixes the error buttons to always use the base domain. The canonical URL is only useful when forming links to the website itself. (Which clicking the domain link itself on the table does do.)

Fix landing page links to not use canonical URL for permalink

---

README.md

The URL was `https://github.com/dhs-ncat/pshtt` but this missed an `s` and should've been `https://github.com/dhs-ncats/pshtt`.

Fix typo in GitHub link for pshtt

---

app/views.py

Reboots the URLs as `/a11y/[whatever]` instead of `/accessibility/[whatever]`, as requested.

Rename accessibility URLs to a11y

---

Makefile
data/update.py

We haven't needed or used the old site-inspector scans, so removing them from the scan.
Adding sslyze, so we get coverage of subdomains for offline analysis.

Stop using inspect scanner, start using sslyze for subdomains

---

.codeclimate.yml

Removes third party packages from the Code Climate score. This should clean up our score quite a bit.
I'm leaving in the complexity and duplication checks, because eventually it might be nice to go back and refactor to fix these, but they're not pressing at all.

Codeclimate config

---

templates/https/guide.html

Was trying to link down specifically to the definition for "Preloaded", and noticed that some of the ``id`` attributes were missing in the guide.

Added extra id attributes to allow deeper linking

---

data/ineligible/analytics.yml

FYI, hud.gov and america.gov have no 2nd level domain endpoint. They redirect to subdomains. Not a best practice, but it is impossible for them to have DAP code on those hostnames, regardless.

Updating ineligible DAP domains

---

deploy/cron.sh

While we still have the scanning living on a persistent box, make sure its auto-deploy process is always taking into account the latest code. This runs a `git pull` before _and_ after the ~40 hour scanning process.

Update oneself during scan-deploy process

---

data/ineligible/analytics.yml

@tdlowden - this would add `nationalbank.gov` to the list since it redirects to https://www.banknet.gov/entrance/default.html.

adding another to the DAP exclusion list

---

data/update.py

As mentioned in https://github.com/18F/domain-scan/issues/138, sslyze is stalling out for unknown reasons. This is the main reason the scans have stalled for the last month on Pulse. Since we're not even using sslyze for actual Pulse stuff, but instead capture it during the scan for other off-band purposes, I'm yanking it from the Pulse pipeline at least temporarily. 
We can do these scans from a separate DotGov server if need be for the near future, while https://github.com/18F/domain-scan/issues/138 is resolved.

Disable sslyze scan for now

---

app/models.py
data/processing.py

This adds the processing of a11y data from the domain-scan repo to the Pulse pipeline. Things it does not do (to come in follow-up PRs):
1) Actually turn on the automatic scanning of a11y data. There are some unresolved issues in the a11y scan that make me want to hold back for now.
2) Switch the presentation layer to use the newly processed data. This is a trivial task, but since the scan is not automatically running yet, it is premature.
3) Generate the data/domains/a11y.csv file. Same reason as above.
Next step is to pull the a11y processing stuff out of domain-scan and clear up the last scanning issues before switching it on. PRs in that repo to come.

Move a11y into the Pulse processing pipeline

---

data/processing.py

I encountered an edge case where the scanned domain used `maxage` instead of `max-age` in its HSTS header. This results in `pshtt` listing `True` in the `HSTS` column but having an empty `HSTS Max Age` column. This in turn gave a `TypeError: unorderable types: NoneType() >= int()` error caused by line 581. We can prevent this by checking if `hsts_age` is `True` in the `if`-statement leading up to that line.
This has the added advantage that HSTS headers with a `max-age` of 0 are also given an HSTS value of 0 (no HSTS) in Pulse instead of an HSTS value of 1 (HSTS with too low max-age). The [RFC specifies](https://tools.ietf.org/html/rfc6797#section-6.1.1) that a `max-age` of 0 means that the HSTS policy should be removed by the user agent. So the intended effect of the website is to have …

Prevent NoneType() >= int()

---

data/update.py

I reverted the previous PR because I forgot the a11y config files. These
two scans take ~45 minutes combined, so this _shouldn't_ impact things
too much. Once we've confirmed that the data looks good, we'll switch
back to the normal scan and only run a11y and customer satisfaction on
the first of the month.

Add third-party and a11y to normal scan

---

data/update.py

Pronouncing it "ally" in my head as opposed to "a-eleven-y" has lead to more typos in this app than anything else.

Fix scan name

---

data/env.py
data/processing.py
data/update.py

This PR (which is to the still-open `measure-subdomains` branch, which will close soon) updates a few things:
* Includes `.fed.us` in the list of suffixes during subdomain discovery. This makes use of a new multi-suffix feature in domain-scan to discover domains with multiple suffixes simultaneously. 
* It also explicitly skips loading `fed.us` as its own Domain, since it's not actually a registerable domain. This wasn't causing an active problem, as there are no websites at `https://fed.us` (nor should there be), but I wanted to be more explicit in the code instead of it just accidentally working. I believe the .gov registry should probably exclude the row for `fed.us` as a domain from the .gov listings. (It should still include `fs.fed.us` and the other registered `fed.us` domains.)
* …

Update Pulse data loading to include fed.us, allow Lambda, and sync with domain-scan

---

data/env.py
meta.yml

This uses the data in https://github.com/GSA/data/tree/master/dotgov-websites to pull in Reverse DNS data from Rapid7 via scans.io, and to use a November 2017 snapshot of Censys.io data, for Pulse's gathering process.

Add Reverse DNS snapshot data and use Censys snapshot data

---

Makefile
data/update.py
templates/https/guide.html

This enables `--lambda` mode for `pshtt` and `sslyze` scans in production. It relies on the `--lambda-profile` flag recently added to domain-scan, to use a separate AWS named profile from the one used to speak to the cloud.gov S3 bucket.
It also documents the use of the Rapid7 Reverse DNS data source for subdomains.

Turn on Lambda in production

---

data/processing.py

This skips loading `sslyze` data when the result is `{"invalid": true}` (which will inevitably happen on some % of scans during a large run), and don't count them towards a %.
Without this, this was causing Pulse to incorrectly assume/display that domains were using SSLv2, SSLv3, and RC4.

Skip invalid sslyze scans and mark as ineligible

---

data/processing.py

The fix in #748 only applied to subdomains, and not to parent domains, due to the differing code paths. This applies the same fix to parent domains.

Fix sslyze invalidity issue when loading parent domains

---

data/processing.py

There was a regression in #750 that led to us showing only one result for DAP, the final entry `youthrules.gov`, and a success rate of 100%.
This happened because only part of the analytics.csv-loading block was indented underneath the conditional that was added to allow processing when analytics.csv was missing in #750.
This was my fault, as I should have tested out #750 empirically before merging -- I eyeballed [the diff](https://github.com/18F/pulse/pull/750/files) and it looked fine, but the diff cuts off before showing the unindented lines.

Fix DAP data display 

---

data/processing.py

The hacky workaround I was using in #748 and #751 to detect situations when connectivity was not established during SSLyze scanning stopped working. 
The better solution would be a field whose value was just true/false on whether connectivity was established, but in its absence, this fixes the hacky workaround so that affected agencies will see some relief ASAP.

Repair detection of SSLyze results where connection couldn't be established

---

templates/https/guide.html
templates/includes/https/header.html

Adds the `pulse@cio.gov` email explicitly to the HTTPS header and HTTPS guidance tabs, to help agencies figure out a contact address if they want to write us with questions.
cc @smarina04

Makes the pulse@cio.gov contact email explicit

---

docs/a11y-instructions.md

The PR to domain-scan at https://github.com/18F/domain-scan/pull/195 moves `scripts/a11y/` to `utils/a11y/`. In anticipation of that change, I've updated the a11y data update docs to reflect this change.
It also pointed to a now-deleted branch, so I updated the `make-lambda-optional` references (which refer to a much older pa11y-specific Lambda tool, not the domain-scan Lambda integration) to point to `master` instead.
It also referenced the `inspect` scanner, which no longer exists in domain-scan, and it looks like the `pshtt` scanner should fill the function identically for what this process uses it for, so I replaced `inspect` with `pshtt`.
cc @micahsaul @gbinal

Update a11y docs to reflect changed directories and inspect->pshtt

---

data/update.py

This will start capturing additional `--meta` details from domain-scan in the CSVs we generate during scans.

Start capturing --meta details in results CSVs

---

data/env.py
meta.yml
templates/https/guide.html

This expands the gathered hostnames to use the `other-websites.csv` source, managed in https://github.com/GSA/data/tree/master/dotgov-websites, and newly contributed to by DHS NCATS via https://github.com/GSA/data/pull/119 and https://github.com/dhs-ncats/gatherer/issues/18.

Use other-websites.csv when gathering hostnames

---

static/js/https/domains.js

This adds a mention of the pulse@cio.gov email contact as part of the instructions given to agencies as they expand the list of services within their domains. This seemed like the least repetitive place to put it so as to have it appear in the table where agency staff are looking, and to those who are the most invested in looking at individual data.

Be even more explicit with the pulse@cio.gov contact address

---

data/env.py
data/processing.py

The `third_parties` scan is crashing, and as a hotfix, I'm disabling the cust_sat and a11y scans from the `data.processing` load script.
This will not disrupt the staging site's ability to update this data, as the data.processing code is not currently used to calculate this data. It remains a separate pipeline.

For now, disable cust_sat and a11y scans

---

static/js/tables.js

This sorts boolean fields on `"Yes"` and `"No"` instead of by `true` and `false`, which apparently doesn't work correctly.
This affected the Customer Satisfaction and DAP tables (which used `Tables.boolean`), but not the HTTPS tables, which is complicated enough to merit its own rendering.

Sort boolean fields properly when using Tables.boolean

---

data/env.py
data/update.py

The domain-scan `gather` command is now stricter about option parsing, and we can't get away with `--parents` doing two things at once anymore. It's better to use `dotgov` as the source name, and let `--parents` be used for supplying the parent domains under which all source results should be scoped.

Split out use of --parents and use "dotgov" for source name

---

manifest.yml

Always serve application with waitress and run with debug mode off on
cloud foundry.
Looks like this was the issue affecting @jeremy-gillikin's fork.

Set pulse environment to a non-default value.

---

templates/about.html
templates/accessibility/guide.html

This fixes the broken link @sidewalkballet reported, and another one I found when I `grep`'d the templates directory.
Fixes #771.

Fix links to .gov domain list

---

data/logger.py
tests/test_logger.py

This PR introduces a very basic logging module that CDS has used on another project. Actually using this module is in a later, separate, PR.
Fairly simple addition, a `get_logger` function that just wraps `logging. getLogger` with some formatting, and a function to extract exception messages from chained exceptions.

Add logger module

---

.gitignore
mypy.ini
pylintrc

This PR adds some sane defaults for linting and type checking configuration.
Currently `pylint` and `mypy` aren't even being used, but we will be integrating it into our CI setup.
These changes combined with the CI configuration are probably the most "CDS specific" of the changes so far, so if you don't want to merge them in, makes sense to me.

Testing configuration files

---

data/processing.py

With the update of the official .gov domain list in https://github.com/GSA/data/pull/136 to include branch name and organization name, this revamps the .gov domain parsing code to handle those fields properly. It also gets rid of some old and hard-to-maintain branch detection code in favor of relying on upstream determination.

Parse branches and organizations in .gov data

---

data/ineligible/analytics.yml

Since now dotgov.gov is a redirect, adding to the exclude list.

Update analytics.yml with dotgov.gov

---

data/processing.py

This avoids treating a non-`"True"` value as `True`.

Fix up boolean_for to be more precise

---

static/js/https/agencies.js
static/js/https/domains.js

Explicitly forcing a sorting `type` of `numeric`. The crypto field was sorting as a string instead of a number, despite returning a number from the `render` function, likely due to the use of a string value (`--`) for non-connectivity via SSLyze.
This fixes that, and also adds `type: "numeric"` to the other columns for good measure.

Fix sorting of the RC4/3DES/SSLv2/SSLv3 column

---

data/processing.py

The `data/processing.py` script was using `subdomain_name` instead of `name` to index reports when sanity-checking them during processing. The `subdomain_name` variable would have referred to the result of unrelated use prior.
It seems to have been practically harmless (the sanity checking was just out of an abundance of caution), and this change doesn't affect the calculated numbers (or create/remove any new warning or exceptions) during data processing at all. It's good to fix it though, since it could have been the cause of new unexpected bugs if the `subdomain_name` value had ever changed, or if another change would have made the sanity-checking necessary or useful.

Was using wrong variable name to sanity check eligible reports

---

data/processing.py

This PR replaces the conditional creation of a `subdomains` key with usage of the  [`setdefault`](https://docs.python.org/3/library/stdtypes.html#dict.setdefault) method.
This will get the key if it exists, and if not it will set the key with a default value and return it.

replace if in check with setdefault

---

data/processing.py

This tweaks the work from the PR @buckley-w-david filed in #795 to avoid colliding with the existing `subdomains` variable. The `setdefault` code works fine, but the use of a local variable named `subdomains` created problems, as it was already in use in that block.
Without this tweak, the `data.processing` module crashes during data import.

Tweak use of setdefault to not collide with existing local variable

---

data/processing.py

This PR refactors the existing pattern of pulling the first line of a csv into a headers list, then using that list to construct a dict from every row to just using the existing functionality in the python csv library DictReader.
One thing that should be noted is that the behavior of this code will be slightly different in the case of csvs without a header row, but I believe that these would also fail with the existing code, just in another way.

change dict_row pattern to instead make use of DictReader

---

static/js/https/agencies.js
static/js/https/domains.js

A couple times, we've had reported that suggest the CSV is getting too aggressively cached. This resolves that by cache-busting the download URL.

Cache-bust CSV download URLs

---

.circleci/config.yml

pip was raising a ContextualVersionConflict due to reusing the same virtualenv between builds. Workaround might be making egg-info before `pip install -e`

TST: Bump CI Python to 3.6.8 and fix pip error

---

README.md

- Removed Gemnasium from README
- Add Snyk from README

Gemnasium has been discontinued. We use Snyk at GSA now.

---

manifest.yml

CF is deprecating cflinuxfs2 at the end of April, 2019.

BLD: bump cf stack to cflinuxfs3
