18F/pulse

package.json
This sends it up to the production site.
=> Deploys pre-alpha header to production

index.html
This updates the header text as requested in #66:
Fixes #66.
=> Update header text

_includes/header.html
=> changing feedback link

assets/js/https/agencies.js
=> Fix for JS error on https/agencies.

_layouts/default.html
=> Adding browser warning for anything below IE9.

pages/about.html
This updates the feedback section to try to direct people to the right place for various kinds of feedback and questions.
=> More detailed contact info on the FAQ

_includes/reporting.html
Ugh, I forgot to link to the actual new JS file in the template.
=> Actually link to the DAP

_includes/reporting.html
I still messed up the last one in #236, and didn't include the `agency` and `subagency` parameters. Done here.
=> Fix DAP snippet...again

pulse.py
Resolves #253. 
Includes first 2 commits to fix up localdev setup & python formatting (4 spaces, no tabs).
=> Convert tabs to spaces in pulse.py to follow pep8

.gitignore, app/helpers.py
This fixes a crash on the (mostly unused) landing pages that was introduced in d0aa6dd4f9f4e458657e14cd6e2af7992cd2dbb1 when moving some functions.
=> Fix domain landing page crash

templates/accessibility/guide.html, templates/includes/accessibility/header.html
Changed language in the header and guidance section based on comments and suggestions from the ME stakeholders. Also moved the "why is this important?" and "limitations" sections closer to the top.
=> Update accessibility language

app/views.py
Comment out routing to all `/accessibility/` pages.
=> Disable Accessibility pages

app/views.py
Reverts 18F/pulse#443 for staging.
=> Revert "Disable Accessibility pages"

templates/accessibility/agencies.html
Adds `<caption>Accessibility by Agency</caption>`
=> Add caption for datatable in Accessibility Agency page

templates/accessibility/agencies.html
to help make the columns on https://staging.pulse.cio.gov/accessibility/agencies/ make more sense.
=> adding 'Total' prefix

Makefile, README.md, app/views.py, data/processing.py, data/update.py, deploy/cron.sh, templates/https/guide.html
In this awkward period where we're dealing with 508 scans and adding some things to the `master` (staging) branch that don't appear in `production`, this backports the `production` changes to minimize the chances of merge conflicts later. 
It should be entirely safe to merge, but it'd be niceif @nickbristow or @adelevie took a look at it to make sure it's not stomping on anything they've done.
=> Backport production changes into master

templates/includes/accessibility/header.html
=> Various content changes

templates/includes/accessibility/header.html
=> reverting section name

app/views.py, static/js/utils.js, templates/accessibility/agencies.html, templates/accessibility/domains.html, templates/accessibility/guide.html
This updates links from the old to the new URLs.
=> More completely rename a11y URLs

data/processing.py
@konklone - take a glance and holler if I'm missing anything.
=> adding a legislative agencies to the list

static/data/tables/accessibility/domains.json
This addresses some of the numbers on the domains page that hadn’t caught up from the 11-14 push.
=> domains.json refresh from 11-14

app/views.py, templates/data.html
Hey @gbinal, this is an old unmerged branch from a previous request you made for a `/data/` page. Want to 👁  it?
=> Placeholder open data page

requirements.txt
Probably not strictly necessary, but it didn't seem to break anything
and it'll make Gemnasium happy.
=> Update dependencies to newest versions

README.md
Shares some infrastructure, directly inspired, seems worth including next to the forks.
=> Mention securethenews in the README

Procfile, manifest.yml, newrelic.ini, requirements.txt
Adds New Relic config and changes how app launches in cloud.gov.
Also updates Flask to most recent version.
=> Add newrelic

templates/a11y.html, templates/includes/accessibility/header.html
Updated a11y scan date in templates.
=> Update scan dates

meta.yml
to help address https://github.com/18F/pulse/issues/664
=> changing analytics_subdomains_url link

static/js/accessibility/agencies.js
dovetails with https://github.com/18F/domain-scan/pull/115
=> semantic changes to a11y scans

static/data/tables/customer-satisfaction/agencies.json, static/data/tables/customer-satisfaction/domains.json, static/js/customer-satisfaction/agencies.js, static/js/customer-satisfaction/domains.js, static/js/utils.js, templates/customer-satisfaction/domains.html
=> Update cust sat

static/data/tables/customer-satisfaction/customer-satisfaction.json, templates/includes/customer-satisfaction/donut.html, templates/includes/customer-satisfaction/header.html
@micahsaul - this is ready to merge and push whenever you're game.
=> MVP the custsat donut

static/data/tables/customer-satisfaction/agencies.json, static/data/tables/customer-satisfaction/customer-satisfaction.json, static/data/tables/customer-satisfaction/domains.json
@micahsaul - game to merge and deploy?
=> adding June cust-sat data

data/update.py
=> Revert "Run a11y and cust-sat on the first of the month"

data/processing.py
This allows the processing portion to complete if one chooses to use only the lambda ready scanners (pshtt, sslyze).
=> Updates to allow processing to contiue without Analystics data

static/js/https/domains.js, static/js/utils.js
This cache-busts some XHR calls to populate the table.
=> Cache bust some XHR calls

setup.py
Greetings from your friends to the north!
As I believe you are aware, the Canadian Digital Service is interested in similar work that prompted 18F to create Pulse, and is thinking of using Pulse as a base to build off of.
In the course of investigating we've made a few refactors to bring it closer in line with how we would structure such a system (with more refactoring changes planned).
This PR is mostly to see if you're interested in incorporating any of the changes we're going to be making.
As of yet not a lot has changed, We've made `data` into a package (This PR), `print`s throughout have been subbed out with calls to methods from the `logging` module, and some small testing has been setup.
Soon however we will be implementing changes that would be breaking backwards compatibility …
=> Data as a package

.gitignore, setup.py
=> BLD: Bump pyyaml and flask dependencies

.gitignore, setup.py
Bumping flask to address CVE-2019-1010083.
=> BLD: bump flask to 1.0.0
